# Copyright 2026 The TensorFlow Metal Plugin Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Writes the table of what this plugin registers, by asking TensorFlow.

The list used to be maintained by hand, which meant it was a claim about the
kernels rather than a description of them, and it drifted: it still named ops
that had been deleted. Asking the kernel registry cannot drift.

The registry is snapshotted before and after loading the plugin, and the
difference is what the plugin added. That matters because TensorFlow already
registers around a hundred ops for a GPU device on its own, and those are not
this plugin's to claim.

Source locations come from the op name's first appearance in the kernels
directory, which is where the registration list holds it.
"""

import argparse
import collections
import os
import pathlib
import subprocess
import sys

os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "3")

import tensorflow as tf  # pylint: disable=g-import-not-at-top
from tensorflow.python.framework import kernels  # pylint: disable=g-import-not-at-top
from tensorflow.python.framework import load_library  # pylint: disable=g-import-not-at-top

ROOT = pathlib.Path(__file__).resolve().parent.parent
KERNEL_DIR = ROOT / "src/tensorflow/core/common_runtime/metal/kernels"
# Relative to docs/, which is where the generated file lives.
KERNEL_DIR_LINK = "../src/tensorflow/core/common_runtime/metal/kernels"


def snapshot():
  """Every GPU registration TensorFlow currently holds, keyed by op."""
  found = collections.defaultdict(set)
  for kernel in kernels.get_all_registered_kernels().kernel:
    if kernel.device_type != "GPU":
      continue
    dtypes = ()
    for constraint in kernel.constraint:
      if constraint.name in ("T", "dtype"):
        dtypes = tuple(sorted(tf.DType(value).name
                              for value in constraint.allowed_values.list.type))
    found[kernel.op].add(
        (dtypes, tuple(sorted(kernel.host_memory_arg))))
  return found


def locate(op):
  """Where the op name appears in the kernels directory, or None."""
  result = subprocess.run(["grep", "-rn", f'"{op}"', str(KERNEL_DIR)],
                          capture_output=True, text=True)
  for line in result.stdout.splitlines():
    path, number, _ = line.split(":", 2)
    return os.path.basename(path), int(number)
  return None


def main():
  parser = argparse.ArgumentParser()
  parser.add_argument("--plugin",
                      default=str(ROOT / "build" / "libmetal_plugin.dylib"))
  parser.add_argument("--output", default=str(ROOT / "docs" / "kernels.md"))
  args = parser.parse_args()

  before = snapshot()
  load_library.load_pluggable_device_library(args.plugin)
  after = snapshot()

  added = {}
  for op, registrations in after.items():
    extra = registrations - before.get(op, set())
    if not extra:
      continue
    added[op] = {
        "dtypes": sorted({d for dtypes, _ in extra for d in dtypes}),
        "host_memory": sorted({h for _, host in extra for h in host}),
        "new": op not in before,
    }

  overlapping = sum(1 for row in added.values() if not row["new"])

  with open(args.output, "w") as out:
    out.write("# Kernels this plugin registers\n\n")
    out.write(
        f"Generated by `make kernels` against TensorFlow {tf.__version__}. "
        "Do not edit by hand.\n\n"
        f"{len(added)} ops. TensorFlow registers {len(before)} more for a GPU "
        "device on its own, before this plugin loads, and those are not "
        "listed here: the table is the difference the plugin makes.\n\n"
        f"{overlapping} of the rows are marked `(adds to TensorFlow's own)`, "
        "meaning TensorFlow already had a GPU registration for that op and "
        "the plugin adds another, for a dtype or a memory placement it did "
        "not cover.\n\n"
        "Dtypes are the `T` or `dtype` constraint as the registry holds it "
        "after registration. Host-memory arguments are inputs or outputs the "
        "registration pins to the host, which is correct but not "
        "accelerated.\n\n")
    out.write("| Op | dtypes | host-memory args | source |\n")
    out.write("| --- | --- | --- | --- |\n")
    for op in sorted(added):
      row = added[op]
      dtypes = ", ".join(row["dtypes"]) or "(no dtype constraint)"
      host = ", ".join(row["host_memory"])
      where = locate(op)
      source = (f"[{where[0]}:{where[1]}]({KERNEL_DIR_LINK}/{where[0]}#L{where[1]})"
                if where else "")
      mark = "" if row["new"] else " (adds to TensorFlow's own)"
      out.write(f"| `{op}`{mark} | {dtypes} | {host} | {source} |\n")

  print(f"wrote {args.output}: {len(added)} ops")
  return 0


if __name__ == "__main__":
  sys.exit(main())
